name: Sync from upstream

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点（UTC）自动运行
  workflow_dispatch:      # 手动触发按钮

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/mt-arb/ar-wallet-sit.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Sync from upstream"

      - name: Push to origin
        run: git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
